/* DON'T EDIT THIS FILE. This is generated by 'scripts/update-src-index.ts' */
import type { TSESLint } from '@typescript-eslint/experimental-utils';

import recommendedModule from './configs/recommended-module';
import recommendedScript from './configs/recommended-script';
import recommended from './configs/recommended';
import callbackReturn from './rules/callback-return';
import exportsStyle from './rules/exports-style';
import fileExtensionInImport from './rules/file-extension-in-import';
import globalRequire from './rules/global-require';
import handleCallbackErr from './rules/handle-callback-err';
import noCallbackLiteral from './rules/no-callback-literal';
import noDeprecatedApi from './rules/no-deprecated-api';
import noExportsAssign from './rules/no-exports-assign';
import noExtraneousImport from './rules/no-extraneous-import';
import noExtraneousRequire from './rules/no-extraneous-require';
import noMissingImport from './rules/no-missing-import';
import noMissingRequire from './rules/no-missing-require';
import noMixedRequires from './rules/no-mixed-requires';
import noNewRequire from './rules/no-new-require';
import noPathConcat from './rules/no-path-concat';
import noProcessEnv from './rules/no-process-env';
import noProcessExit from './rules/no-process-exit';
import noRestrictedImport from './rules/no-restricted-import';
import noRestrictedRequire from './rules/no-restricted-require';
import noSync from './rules/no-sync';
import noUnpublishedBin from './rules/no-unpublished-bin';
import noUnpublishedImport from './rules/no-unpublished-import';
import noUnpublishedRequire from './rules/no-unpublished-require';
import noUnsupportedFeaturesEsBuiltins from './rules/no-unsupported-features/es-builtins';
import noUnsupportedFeaturesEsSyntax from './rules/no-unsupported-features/es-syntax';
import noUnsupportedFeaturesNodeBuiltins from './rules/no-unsupported-features/node-builtins';
import preferGlobalBuffer from './rules/prefer-global/buffer';
import preferGlobalConsole from './rules/prefer-global/console';
import preferGlobalProcess from './rules/prefer-global/process';
import preferGlobalTextDecoder from './rules/prefer-global/text-decoder';
import preferGlobalTextEncoder from './rules/prefer-global/text-encoder';
import preferGlobalUrlSearchParams from './rules/prefer-global/url-search-params';
import preferGlobalUrl from './rules/prefer-global/url';
import preferPromisesDns from './rules/prefer-promises/dns';
import preferPromisesFs from './rules/prefer-promises/fs';
import processExitAsThrow from './rules/process-exit-as-throw';
import shebang from './rules/shebang';

export default {
  configs: {
    'recommended-module': recommendedModule,
    'recommended-script': recommendedScript,
    get recommended(): TSESLint.Linter.Config {
      return recommended();
    },
  },
  rules: {
    'callback-return': callbackReturn,
    'exports-style': exportsStyle,
    'file-extension-in-import': fileExtensionInImport,
    'global-require': globalRequire,
    'handle-callback-err': handleCallbackErr,
    'no-callback-literal': noCallbackLiteral,
    'no-deprecated-api': noDeprecatedApi,
    'no-exports-assign': noExportsAssign,
    'no-extraneous-import': noExtraneousImport,
    'no-extraneous-require': noExtraneousRequire,
    'no-missing-import': noMissingImport,
    'no-missing-require': noMissingRequire,
    'no-mixed-requires': noMixedRequires,
    'no-new-require': noNewRequire,
    'no-path-concat': noPathConcat,
    'no-process-env': noProcessEnv,
    'no-process-exit': noProcessExit,
    'no-restricted-import': noRestrictedImport,
    'no-restricted-require': noRestrictedRequire,
    'no-sync': noSync,
    'no-unpublished-bin': noUnpublishedBin,
    'no-unpublished-import': noUnpublishedImport,
    'no-unpublished-require': noUnpublishedRequire,
    'no-unsupported-features/es-builtins': noUnsupportedFeaturesEsBuiltins,
    'no-unsupported-features/es-syntax': noUnsupportedFeaturesEsSyntax,
    'no-unsupported-features/node-builtins': noUnsupportedFeaturesNodeBuiltins,
    'prefer-global/buffer': preferGlobalBuffer,
    'prefer-global/console': preferGlobalConsole,
    'prefer-global/process': preferGlobalProcess,
    'prefer-global/text-decoder': preferGlobalTextDecoder,
    'prefer-global/text-encoder': preferGlobalTextEncoder,
    'prefer-global/url-search-params': preferGlobalUrlSearchParams,
    'prefer-global/url': preferGlobalUrl,
    'prefer-promises/dns': preferPromisesDns,
    'prefer-promises/fs': preferPromisesFs,
    'process-exit-as-throw': processExitAsThrow,
    shebang,
  },
};
